kind: pipeline
name: default
workspace:
  path: /drone/src

steps:
  - name: fetch beets version
    image: alpine
    commands:
      - apk add --no-cache curl jq
      - >
        sh -c "curl -s https://pypi.org/pypi/beets/json > pypi.json &&
        BEETS_VERSION=\$(jq -r '.info.version' pypi.json) &&
        echo BEETS_VERSION=\$BEETS_VERSION &&
        echo BEETS_VERSION=\$BEETS_VERSION > build.env"

  - name: debug and load env
    image: alpine
    environment:
      from_file: /drone/src/build.env
    commands:
      - env
      - source build.env
      - echo "Beets version is $BEETS_VERSION"
      - echo "BEETS_VERSION=${BEETS_VERSION}" >> /drone/src/.drone.env

#  - name: build and push to GHCR
#    image: plugins/docker
#    environment:
#      from_file: /drone/src/build.env
#    settings:
#      registry: ghcr.io
#      username: stefannitsche
#      password:
#        from_secret: github_registry
#      repo: ghcr.io/stefannitsche/beets
#      build_args_from_env:
#        - BEETS_VERSION
#      tags:
#        - latest
#        - ${BEETS_VERSION}
#        - ${BEETS_VERSION}.${DRONE_BUILD_NUMBER}
#      purge: true
#      pull_image: true
#      no_cache: true

  - name: build and push to GHCR
    image: docker:cli
    environment:
      GITHUB_REGISTRY:
        from_secret: github_registry
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - echo "Reading BEETS_VERSION from build.env"
      - source build.env
      - echo "Using BEETS_VERSION=$BEETS_VERSION"
      - docker build --rm=true --pull --no-cache --build-arg BEETS_VERSION=$BEETS_VERSION -t ghcr.io/stefannitsche/beets:latest -t ghcr.io/stefannitsche/beets:$BEETS_VERSION -t ghcr.io/stefannitsche/beets:$BEETS_VERSION.$DRONE_BUILD_NUMBER .
      - echo "$GITHUB_REGISTRY" | docker login ghcr.io -u stefannitsche --password-stdin
      - docker push ghcr.io/stefannitsche/beets:latest
      - docker push ghcr.io/stefannitsche/beets:$BEETS_VERSION
      - docker push ghcr.io/stefannitsche/beets:$BEETS_VERSION.$DRONE_BUILD_NUMBER

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
