kind: pipeline
name: default
workspace:
  path: /drone/src

steps:
  - name: fetch beets version
    image: alpine
    commands:
      - apk add --no-cache curl jq
      - curl -s https://pypi.org/pypi/beets/json -o pypi.json
      - cat pypi.json
      - jq -r '.info.version' pypi.json
      - BEETS_VERSION=$(jq -r '.info.version' pypi.json)
      - echo "BEETS_VERSION=${BEETS_VERSION}" > build.env

  - name: debug env
    image: alpine
    environment:
      from_file: /drone/src/build.env
    commands:
      - echo "Beets version is $BEETS_VERSION"

  - name: build and push to GHCR
    image: plugins/docker
    settings:
      registry: ghcr.io
      username: stefannitsche
      password:
        from_secret: github_registry
      repo: ghcr.io/stefannitsche/beets
      build_args:
        - BEETS_VERSION=${BEETS_VERSION}
      tags:
        - latest
        - ${BEETS_VERSION}
        - ${BEETS_VERSION}.${DRONE_BUILD_NUMBER}
      purge: true
      pull_image: true
      no_cache: true
    environment:
      from_file: /drone/src/build.env
