# Edit this file to fit your system.

directory: /data/Audio/Library/Music # Destination
library: /config/musiclibrary.blb # Database
#pluginpath:
  #- ~/.config/beets/beetsplug/fetchartist # https://github.com/dkanada/beets-fetchartist
  #- ~/.config/beets/beetsplug/discogs_extradata
