#!/command/with-contenv bash
# shellcheck shell=bash

chown 99:100 /config
# copy config
su -c "cp -n /defaults/beets/secrets.yaml /config/secrets.yaml" app
su -c "cp -n /defaults/beets/plugins.yaml /config/plugins.yaml" app
su -c "mkdir -p /config/genres" app
su -c "cp -n /defaults/beets/genres/genres-tree.yaml /config/genres/genres-trees.yaml" app
su -c "cp -n /defaults/beets/genres/genres.txt /config/genres/genres.txt" app
su -c "cp -n /defaults/beets/config.yaml /config/config.yaml" app
chown -R 99:100 /config
